name: Update GitHub Activity Log

on:
  schedule:
    - cron: '0 */12 * * *'   # 每 12 小時自動執行
  workflow_dispatch:          # 可手動觸發
  push:
    branches:
      - main

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_TOKEN: ${{ secrets.TOKEN }}
          MAX_LINES: 10
          README_PATH: 'README.md'