name: Update GitHub Activity Log

on:
  schedule:
    - cron: '0 */12 * * *'   # 每 12 小時自動執行
  workflow_dispatch:          # 可手動觸發
  push:
    branches:
      - main

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      
      - name: Update GitHub Activity
        uses: ggofri/github-activity-updater@v1
        with:
          github-token: ${{ secrets.TOKEN }}
          username: saisai568